### ISSUE TITLE
[pytype 2018.11.06] CRITICAL Cannot parse input files:

### ISSUE THREAD

**Issue by byllyfish** [google/pytype#194]
Just upgraded to the newest pytype from pypi (2018.11.06) on Mac OS X. My test script runs pytype as:

pytype -V 3.6 MODULE

This worked fine with '2018.10.30'. It now immediately fails with an error:

```
CRITICAL Cannot parse input files:
create() got an unexpected keyword argument 'trim'
```

pytype-single on a file still works fine. Calling pytype on an individual source file fails with the same error.

The easiest way to reproduce this is:

```
$ touch somefile.py
$ pytype -v 2 -V 3.6 somefile.py 
INFO No config file specified, and no [pytype] section in setup.cfg. Using default configuration.
INFO Configuration:
  exclude = set()
  inputs = {'/Users/bfish/code/zof/somefile.py'}
  output = '/Users/bfish/code/zof/pytype_output'
  pythonpath = ['/Users/bfish/code/zof']
  python_version = '3.6'
  disable = []
  report_errors = True
  protocols = False
  strict_import = False
CRITICAL Cannot parse input files:
create() got an unexpected keyword argument 'trim'
```

Thanks!

**Comment by byllyfish** [comment]
Sorry, it was caused by an install/upgrade issue. I upgraded Python 3.6, created a new virtual 3.6 environment, and re-installed pytype. This time it worked fine.

Looking deeper, my existing importlab version was 0.3.1.  Upgrading importlab to 0.4 fixed the issue. The setup.py install_requires line might need a '(>=0.4)' specifier.

**Comment by rchen152** [comment]
That looks like it's happening because the newest pytype version requires importlab-0.4, in which the `trim` option was added. Could you see if updating importlab fixes the issue?

On our end, we should change setup.py to require the right importlab version.

**Comment by byllyfish** [comment]
Just confirming that updating importlab fixed the issue. :)

Thanks for the quick response!!
