### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by wieczorek1990** [google/pytype#1308]
Tried to build with Python 3.11 and this is the output:

```
  Building wheel for pytype (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pytype (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [566 lines of output]
      /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'pytype.typegraph.cfg' extension
      In file included from pytype/typegraph/cfg.cc:1:
      In file included from /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:45:
      In file included from /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/attr.h:13:
      /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/cast.h:446:36: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
                      "  " + handle(frame->f_code->co_filename).cast<std::string>() +
                                         ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      In file included from pytype/typegraph/cfg.cc:1:
      In file included from /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:45:
      In file included from /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/attr.h:13:
      /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/cast.h:448:29: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
                      handle(frame->f_code->co_name).cast<std::string>() + "\n";
                                  ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      In file included from pytype/typegraph/cfg.cc:1:
      In file included from /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:45:
      In file included from /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/attr.h:13:
      /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/cast.h:449:26: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
                  frame = frame->f_back;
                               ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      In file included from pytype/typegraph/cfg.cc:1:
      /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:2210:49: error: no member named 'frame' in '_ts'
          PyFrameObject *frame = PyThreadState_Get()->frame;
                                 ~~~~~~~~~~~~~~~~~~~  ^
      /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:2211:41: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
          if (frame && (std::string) str(frame->f_code->co_name) == name &&
                                              ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      In file included from pytype/typegraph/cfg.cc:1:
      /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:2212:14: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
              frame->f_code->co_argcount > 0) {
                   ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      In file included from pytype/typegraph/cfg.cc:1:
      /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:2215:18: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
                  frame->f_locals, PyTuple_GET_ITEM(frame->f_code->co_varnames, 0));
                       ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      In file included from pytype/typegraph/cfg.cc:1:
      /private/var/folders/_l/49d5phzs6tgf325gmsp5xljr0000gn/T/pip-build-env-ixsnf6o5/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:2215:52: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
                  frame->f_locals, PyTuple_GET_ITEM(frame->f_code->co_varnames, 0));
                                                         ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      pytype/typegraph/cfg.cc:505:42: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        PyVarObject_HEAD_INIT(&PyType_Type, 0) tp_name : "Program",
                                               ^~~~~~~~~
                                               .tp_name =
      pytype/typegraph/cfg.cc:506:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_basicsize : sizeof(PyProgramObj),
        ^~~~~~~~~~~~~~
        .tp_basicsize =
      pytype/typegraph/cfg.cc:507:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_itemsize : 0,
        ^~~~~~~~~~~~~
        .tp_itemsize =
      pytype/typegraph/cfg.cc:508:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_dealloc : ProgramDealloc,
        ^~~~~~~~~~~~
        .tp_dealloc =
      pytype/typegraph/cfg.cc:510:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_vectorcall_offset: -1,
        ^~~~~~~~~~~~~~~~~~~~~
        .tp_vectorcall_offset =
      pytype/typegraph/cfg.cc:514:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_getattr : nullptr,
        ^~~~~~~~~~~~
        .tp_getattr =
      pytype/typegraph/cfg.cc:515:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_setattr : nullptr,
        ^~~~~~~~~~~~
        .tp_setattr =
      pytype/typegraph/cfg.cc:517:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_async : nullptr,
        ^~~~~~~~~~~~~
        .tp_as_async =
      pytype/typegraph/cfg.cc:521:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_repr : nullptr,
        ^~~~~~~~~
        .tp_repr =
      pytype/typegraph/cfg.cc:522:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_number : nullptr,
        ^~~~~~~~~~~~~~
        .tp_as_number =
      pytype/typegraph/cfg.cc:523:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_sequence : nullptr,
        ^~~~~~~~~~~~~~~~
        .tp_as_sequence =
      pytype/typegraph/cfg.cc:524:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_mapping : nullptr,
        ^~~~~~~~~~~~~~~
        .tp_as_mapping =
      pytype/typegraph/cfg.cc:525:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_hash : nullptr,
        ^~~~~~~~~
        .tp_hash =
      pytype/typegraph/cfg.cc:526:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_call : nullptr,
        ^~~~~~~~~
        .tp_call =
      pytype/typegraph/cfg.cc:527:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_str : nullptr,
        ^~~~~~~~
        .tp_str =
      pytype/typegraph/cfg.cc:528:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_getattro : ProgramGetAttro,
        ^~~~~~~~~~~~~
        .tp_getattro =
      pytype/typegraph/cfg.cc:529:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_setattro : ProgramSetAttro,
        ^~~~~~~~~~~~~
        .tp_setattro =
      pytype/typegraph/cfg.cc:530:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_buffer : nullptr,
        ^~~~~~~~~~~~~~
        .tp_as_buffer =
      pytype/typegraph/cfg.cc:531:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_flags : 0,
        ^~~~~~~~~~
        .tp_flags =
      pytype/typegraph/cfg.cc:532:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_doc : program_doc,
        ^~~~~~~~
        .tp_doc =
      pytype/typegraph/cfg.cc:533:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_traverse : nullptr,
        ^~~~~~~~~~~~~
        .tp_traverse =
      pytype/typegraph/cfg.cc:534:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_clear : nullptr,
        ^~~~~~~~~~
        .tp_clear =
      pytype/typegraph/cfg.cc:535:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_richcompare : nullptr,
        ^~~~~~~~~~~~~~~~
        .tp_richcompare =
      pytype/typegraph/cfg.cc:536:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_weaklistoffset : 0,
        ^~~~~~~~~~~~~~~~~~~
        .tp_weaklistoffset =
      pytype/typegraph/cfg.cc:537:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_iter : nullptr,
        ^~~~~~~~~
        .tp_iter =
      pytype/typegraph/cfg.cc:538:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_iternext : nullptr,
        ^~~~~~~~~~~~~
        .tp_iternext =
      pytype/typegraph/cfg.cc:539:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_methods : program_methods,
        ^~~~~~~~~~~~
        .tp_methods =
      pytype/typegraph/cfg.cc:540:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_members : nullptr,
        ^~~~~~~~~~~~
        .tp_members =
      pytype/typegraph/cfg.cc:541:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_getset : nullptr,
        ^~~~~~~~~~~
        .tp_getset =
      pytype/typegraph/cfg.cc:542:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_base : nullptr,
        ^~~~~~~~~
        .tp_base =
      pytype/typegraph/cfg.cc:543:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_dict : nullptr,
        ^~~~~~~~~
        .tp_dict =
      pytype/typegraph/cfg.cc:544:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_descr_get : nullptr,
        ^~~~~~~~~~~~~~
        .tp_descr_get =
      pytype/typegraph/cfg.cc:545:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_descr_set : nullptr,
        ^~~~~~~~~~~~~~
        .tp_descr_set =
      pytype/typegraph/cfg.cc:546:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_dictoffset : 0,
        ^~~~~~~~~~~~~~~
        .tp_dictoffset =
      pytype/typegraph/cfg.cc:547:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_init : nullptr,
        ^~~~~~~~~
        .tp_init =
      pytype/typegraph/cfg.cc:548:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_alloc : nullptr,
        ^~~~~~~~~~
        .tp_alloc =
      pytype/typegraph/cfg.cc:549:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_new : ProgramNew,
        ^~~~~~~~
        .tp_new =
      pytype/typegraph/cfg.cc:770:42: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        PyVarObject_HEAD_INIT(&PyType_Type, 0) tp_name : "CFGNode",
                                               ^~~~~~~~~
                                               .tp_name =
      pytype/typegraph/cfg.cc:771:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_basicsize : sizeof(PyCFGNodeObj),
        ^~~~~~~~~~~~~~
        .tp_basicsize =
      pytype/typegraph/cfg.cc:772:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_itemsize : 0,
        ^~~~~~~~~~~~~
        .tp_itemsize =
      pytype/typegraph/cfg.cc:773:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_dealloc : CFGNodeDealloc,
        ^~~~~~~~~~~~
        .tp_dealloc =
      pytype/typegraph/cfg.cc:775:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_vectorcall_offset: -1,
        ^~~~~~~~~~~~~~~~~~~~~
        .tp_vectorcall_offset =
      pytype/typegraph/cfg.cc:779:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_getattr : nullptr,
        ^~~~~~~~~~~~
        .tp_getattr =
      pytype/typegraph/cfg.cc:780:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_setattr : nullptr,
        ^~~~~~~~~~~~
        .tp_setattr =
      pytype/typegraph/cfg.cc:782:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_async : nullptr,
        ^~~~~~~~~~~~~
        .tp_as_async =
      pytype/typegraph/cfg.cc:786:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_repr : CFGNodeRepr,
        ^~~~~~~~~
        .tp_repr =
      pytype/typegraph/cfg.cc:787:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_number : nullptr,
        ^~~~~~~~~~~~~~
        .tp_as_number =
      pytype/typegraph/cfg.cc:788:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_sequence : nullptr,
        ^~~~~~~~~~~~~~~~
        .tp_as_sequence =
      pytype/typegraph/cfg.cc:789:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_mapping : nullptr,
        ^~~~~~~~~~~~~~~
        .tp_as_mapping =
      pytype/typegraph/cfg.cc:790:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_hash : nullptr,
        ^~~~~~~~~
        .tp_hash =
      pytype/typegraph/cfg.cc:791:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_call : nullptr,
        ^~~~~~~~~
        .tp_call =
      pytype/typegraph/cfg.cc:792:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_str : CFGNodeRepr,
        ^~~~~~~~
        .tp_str =
      pytype/typegraph/cfg.cc:793:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_getattro : CFGNodeGetAttro,
        ^~~~~~~~~~~~~
        .tp_getattro =
      pytype/typegraph/cfg.cc:794:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_setattro : CFGNodeSetAttro,
        ^~~~~~~~~~~~~
        .tp_setattro =
      pytype/typegraph/cfg.cc:795:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_buffer : nullptr,
        ^~~~~~~~~~~~~~
        .tp_as_buffer =
      pytype/typegraph/cfg.cc:796:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_flags : 0,
        ^~~~~~~~~~
        .tp_flags =
      pytype/typegraph/cfg.cc:797:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_doc : cfg_node_doc,
        ^~~~~~~~
        .tp_doc =
      pytype/typegraph/cfg.cc:798:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_traverse : nullptr,
        ^~~~~~~~~~~~~
        .tp_traverse =
      pytype/typegraph/cfg.cc:799:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_clear : nullptr,
        ^~~~~~~~~~
        .tp_clear =
      pytype/typegraph/cfg.cc:800:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_richcompare : nullptr,
        ^~~~~~~~~~~~~~~~
        .tp_richcompare =
      pytype/typegraph/cfg.cc:801:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_weaklistoffset : 0,
        ^~~~~~~~~~~~~~~~~~~
        .tp_weaklistoffset =
      pytype/typegraph/cfg.cc:802:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_iter : nullptr,
        ^~~~~~~~~
        .tp_iter =
      pytype/typegraph/cfg.cc:803:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_iternext : nullptr,
        ^~~~~~~~~~~~~
        .tp_iternext =
      pytype/typegraph/cfg.cc:804:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_methods : cfg_node_methods,
        ^~~~~~~~~~~~
        .tp_methods =
      pytype/typegraph/cfg.cc:825:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        name: const_cast<char*>("Origin"),
        ^~~~~
        .name =
      pytype/typegraph/cfg.cc:826:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        doc: origin_doc,
        ^~~~
        .doc =
      pytype/typegraph/cfg.cc:827:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        fields: origin_fields,
        ^~~~~~~
        .fields =
      pytype/typegraph/cfg.cc:828:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        n_in_sequence: 2,
        ^~~~~~~~~~~~~~
        .n_in_sequence =
      pytype/typegraph/cfg.cc:1006:42: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        PyVarObject_HEAD_INIT(&PyType_Type, 0) tp_name : "Binding",
                                               ^~~~~~~~~
                                               .tp_name =
      pytype/typegraph/cfg.cc:1007:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_basicsize : sizeof(PyBindingObj),
        ^~~~~~~~~~~~~~
        .tp_basicsize =
      pytype/typegraph/cfg.cc:1008:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_itemsize : 0,
        ^~~~~~~~~~~~~
        .tp_itemsize =
      pytype/typegraph/cfg.cc:1009:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_dealloc : BindingDealloc,
        ^~~~~~~~~~~~
        .tp_dealloc =
      pytype/typegraph/cfg.cc:1011:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_vectorcall_offset: -1,
        ^~~~~~~~~~~~~~~~~~~~~
        .tp_vectorcall_offset =
      pytype/typegraph/cfg.cc:1015:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_getattr : nullptr,
        ^~~~~~~~~~~~
        .tp_getattr =
      pytype/typegraph/cfg.cc:1016:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_setattr : nullptr,
        ^~~~~~~~~~~~
        .tp_setattr =
      pytype/typegraph/cfg.cc:1018:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_async : nullptr,
        ^~~~~~~~~~~~~
        .tp_as_async =
      pytype/typegraph/cfg.cc:1022:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_repr : BindingRepr,
        ^~~~~~~~~
        .tp_repr =
      pytype/typegraph/cfg.cc:1023:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_number : nullptr,
        ^~~~~~~~~~~~~~
        .tp_as_number =
      pytype/typegraph/cfg.cc:1024:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_sequence : nullptr,
        ^~~~~~~~~~~~~~~~
        .tp_as_sequence =
      pytype/typegraph/cfg.cc:1025:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_mapping : nullptr,
        ^~~~~~~~~~~~~~~
        .tp_as_mapping =
      pytype/typegraph/cfg.cc:1026:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_hash : nullptr,
        ^~~~~~~~~
        .tp_hash =
      pytype/typegraph/cfg.cc:1027:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_call : nullptr,
        ^~~~~~~~~
        .tp_call =
      pytype/typegraph/cfg.cc:1028:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_str : BindingRepr,
        ^~~~~~~~
        .tp_str =
      pytype/typegraph/cfg.cc:1029:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_getattro : BindingGetAttro,
        ^~~~~~~~~~~~~
        .tp_getattro =
      pytype/typegraph/cfg.cc:1030:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_setattro : nullptr,
        ^~~~~~~~~~~~~
        .tp_setattro =
      pytype/typegraph/cfg.cc:1031:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_buffer : nullptr,
        ^~~~~~~~~~~~~~
        .tp_as_buffer =
      pytype/typegraph/cfg.cc:1032:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_flags : 0,
        ^~~~~~~~~~
        .tp_flags =
      pytype/typegraph/cfg.cc:1033:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_doc : binding_doc,
        ^~~~~~~~
        .tp_doc =
      pytype/typegraph/cfg.cc:1034:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_traverse : nullptr,
        ^~~~~~~~~~~~~
        .tp_traverse =
      pytype/typegraph/cfg.cc:1035:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_clear : nullptr,
        ^~~~~~~~~~
        .tp_clear =
      pytype/typegraph/cfg.cc:1036:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_richcompare : nullptr,
        ^~~~~~~~~~~~~~~~
        .tp_richcompare =
      pytype/typegraph/cfg.cc:1037:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_weaklistoffset : 0,
        ^~~~~~~~~~~~~~~~~~~
        .tp_weaklistoffset =
      pytype/typegraph/cfg.cc:1038:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_iter : nullptr,
        ^~~~~~~~~
        .tp_iter =
      pytype/typegraph/cfg.cc:1039:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_iternext : nullptr,
        ^~~~~~~~~~~~~
        .tp_iternext =
      pytype/typegraph/cfg.cc:1040:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_methods : binding_methods,
        ^~~~~~~~~~~~
        .tp_methods =
      pytype/typegraph/cfg.cc:1405:42: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        PyVarObject_HEAD_INIT(&PyType_Type, 0) tp_name : "Variable",
                                               ^~~~~~~~~
                                               .tp_name =
      pytype/typegraph/cfg.cc:1406:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_basicsize : sizeof(PyVariableObj),
        ^~~~~~~~~~~~~~
        .tp_basicsize =
      pytype/typegraph/cfg.cc:1407:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_itemsize : 0,
        ^~~~~~~~~~~~~
        .tp_itemsize =
      pytype/typegraph/cfg.cc:1408:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_dealloc : VariableDealloc,
        ^~~~~~~~~~~~
        .tp_dealloc =
      pytype/typegraph/cfg.cc:1410:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_vectorcall_offset: -1,
        ^~~~~~~~~~~~~~~~~~~~~
        .tp_vectorcall_offset =
      pytype/typegraph/cfg.cc:1414:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_getattr : nullptr,
        ^~~~~~~~~~~~
        .tp_getattr =
      pytype/typegraph/cfg.cc:1415:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_setattr : nullptr,
        ^~~~~~~~~~~~
        .tp_setattr =
      pytype/typegraph/cfg.cc:1417:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_async : nullptr,
        ^~~~~~~~~~~~~
        .tp_as_async =
      pytype/typegraph/cfg.cc:1421:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_repr : VariableRepr,
        ^~~~~~~~~
        .tp_repr =
      pytype/typegraph/cfg.cc:1422:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_number : nullptr,
        ^~~~~~~~~~~~~~
        .tp_as_number =
      pytype/typegraph/cfg.cc:1423:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_sequence : nullptr,
        ^~~~~~~~~~~~~~~~
        .tp_as_sequence =
      pytype/typegraph/cfg.cc:1424:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_mapping : nullptr,
        ^~~~~~~~~~~~~~~
        .tp_as_mapping =
      pytype/typegraph/cfg.cc:1425:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_hash : nullptr,
        ^~~~~~~~~
        .tp_hash =
      pytype/typegraph/cfg.cc:1426:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_call : nullptr,
        ^~~~~~~~~
        .tp_call =
      pytype/typegraph/cfg.cc:1427:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_str : VariableRepr,
        ^~~~~~~~
        .tp_str =
      pytype/typegraph/cfg.cc:1428:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_getattro : VariableGetAttro,
        ^~~~~~~~~~~~~
        .tp_getattro =
      pytype/typegraph/cfg.cc:1429:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_setattro : VariableSetAttro,
        ^~~~~~~~~~~~~
        .tp_setattro =
      pytype/typegraph/cfg.cc:1430:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_as_buffer : nullptr,
        ^~~~~~~~~~~~~~
        .tp_as_buffer =
      pytype/typegraph/cfg.cc:1431:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_flags : 0,
        ^~~~~~~~~~
        .tp_flags =
      pytype/typegraph/cfg.cc:1432:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_doc : variable_doc,
        ^~~~~~~~
        .tp_doc =
      pytype/typegraph/cfg.cc:1433:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_traverse : nullptr,
        ^~~~~~~~~~~~~
        .tp_traverse =
      pytype/typegraph/cfg.cc:1434:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_clear : nullptr,
        ^~~~~~~~~~
        .tp_clear =
      pytype/typegraph/cfg.cc:1435:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_richcompare : nullptr,
        ^~~~~~~~~~~~~~~~
        .tp_richcompare =
      pytype/typegraph/cfg.cc:1436:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_weaklistoffset : 0,
        ^~~~~~~~~~~~~~~~~~~
        .tp_weaklistoffset =
      pytype/typegraph/cfg.cc:1437:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_iter : nullptr,
        ^~~~~~~~~
        .tp_iter =
      pytype/typegraph/cfg.cc:1438:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_iternext : nullptr,
        ^~~~~~~~~~~~~
        .tp_iternext =
      pytype/typegraph/cfg.cc:1439:3: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tp_methods : variable_methods,
        ^~~~~~~~~~~~
        .tp_methods =
      In file included from pytype/typegraph/cfg.cc:11:
      In file included from pytype/typegraph/cfg_logging.h:6:
      pytype/typegraph/pylogging.h:64:22: warning: private field 'stream_' is not used [-Wunused-private-field]
        std::stringstream* stream_;
                           ^
      pytype/typegraph/pylogging.h:66:15: warning: private field 'method_name_' is not used [-Wunused-private-field]
        const char* method_name_;
                    ^
      pytype/typegraph/pylogging.h:67:13: warning: private field 'log_object_' is not used [-Wunused-private-field]
        PyObject* log_object_;
                  ^
      125 warnings and 8 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytype
Successfully built autobahn django-simple-history iso-639 psycopg2-binary pyrsistent sendgrid-django wrapt zope-interface lazy-object-proxy libcst django-role-permissions
Failed to build pytype
ERROR: Could not build wheels for pytype, which is required to install pyproject.toml-based projects
```

**Comment by nth10sd** [comment]
For reference for Python 3.11, 0f71fc32545bf1a233471950b203892c15f0b84b enabled Python 3.10 support only about half a year after release of the new Python.

**Comment by rchen152** [comment]
pytype doesn't support Python 3.11 yet. Some very old versions of pytype don't set `python_requires` correctly, so that's probably what you're getting when you try to install pytype in 3.11.

**Comment by FeryET** [comment]
Is pytype usuable in Python 3.11 yet?

**Comment by martindemello** [comment]
no, but we are actively working on it now, it should be usable in the next couple of months

**Comment by rchen152** [comment]
The next pytype version will support 3.11. I'll update here once that's released.

**Comment by rchen152** [comment]
Ok, pytype-2023.10.17 has *basic* 3.11 support. Basic means that we don't yet fully support new 3.11 typing features. We have partial support for typing.dataclass_transform, and typing.Self is being actively worked on (https://github.com/google/pytype/issues/1283).

You can see the status of pytype support for various typing features here: https://google.github.io/pytype/support.html#typing. If there's a feature you'd like to use that don't yet have a tracking issue listed on that page, feel free to open one - it helps us with prioritization.

**Comment by austinnichols101** [comment]
Just an FYI...

Python 3.11 released 2022-10-24
Python 3.12 released 2023-10-02
